;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[bar/main]
include-file = "~/.config/polybar/fonts.ini"

width = 100%
height = 25
bottom = false

background = ${colors.base}
foreground = ${colors.text}

padding-left = 1
padding-right = 1
line-size = 1

border-size = 5
border-color = ${colors.base}

modules-left = workspaces 
modules-center = time 
modules-right = network empty-space backlight empty-space audio empty-space cpu empty-space memory empty-space battery empty-space powermenu

cursor-click = pointer
cursor-scroll = ns-resize
